# Generated by Django 5.1 on 2024-10-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InswapperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upscale', models.IntegerField(help_text='default=8', verbose_name='upscale')),
                ('codeformer_fidelity', models.FloatField(help_text='default=0.90', verbose_name='codeformer_fidelity')),
            ],
            options={
                'verbose_name': 'Inswapper config',
                'verbose_name_plural': 'Inswapper configs',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255, verbose_name='Какое-то произвольное имя сервера')),
                ('server_adress', models.CharField(max_length=255, verbose_name='IP или URL адрес сервера')),
                ('server_port', models.IntegerField(verbose_name='Порт, на который необходимо стучаться')),
                ('server_auth_token', models.CharField(max_length=255, verbose_name='Уникальный токен сервера')),
                ('server_max_process', models.IntegerField(verbose_name='Максимальное кол-во процессов генерации на сервере')),
                ('last_rec_date', models.DateTimeField(default='', verbose_name='Дата последнего запроса на сервер')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Сервера',
            },
        ),
    ]
