# Generated by Django 5.1.1 on 2024-12-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус сервера'),
        ),
    ]
