# Generated by Django 5.1 on 2024-10-02 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='ID Telegram')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия пользователя')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Username пользователя')),
                ('language', models.CharField(blank=True, max_length=250, null=True, verbose_name='Язык пользователя')),
                ('premium', models.BooleanField(blank=True, default=False, null=True, verbose_name='Имеет ли пользователь премиум-аккаунт')),
                ('generation', models.BooleanField(default=False, verbose_name='Выполняется ли генерация?')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_storage/', verbose_name='Хранилище фоток')),
            ],
            options={
                'verbose_name': 'Исходник',
                'verbose_name_plural': 'Исходники',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=100)),
                ('is_activ', models.BooleanField(default=False, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
        migrations.CreateModel(
            name='GenerationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_status', models.CharField(choices=[('ACCEPTED', 'Процесс принят сервером на генерацию'), ('COMPLETED', 'Генерация успешно завершена'), ('WAITING', 'Генерация ожидает принятия сервером')], max_length=110)),
                ('process_backend_id', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_completed', models.DateTimeField(blank=True, default=None, null=True)),
                ('task_end_handler', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хендлер завершения таска')),
                ('output_photo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='output_photo', to='bot_app.images', verbose_name='Полученное фото после генерации')),
                ('photo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='photo', to='bot_app.images', verbose_name='Загруженное изображение')),
                ('target_photo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='target_photo', to='bot_app.images', verbose_name='На кого будет наложено')),
            ],
            options={
                'verbose_name': 'Созданный процесс',
                'verbose_name_plural': 'Созданные процессы',
            },
        ),
    ]
