# Generated by Django 5.1 on 2024-10-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationprocess',
            name='process_status',
            field=models.CharField(choices=[('ACCEPTED', 'Процесс принят сервером на генерацию'), ('COMPLETED', 'Генерация успешно завершена'), ('WAITING', 'Генерация ожидает принятия сервером'), ('ERROR_GENERATION', 'Ошибка генерации')], max_length=110),
        ),
    ]
