# Generated by Django 5.1 on 2024-10-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_alter_generationprocess_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationprocess',
            name='server_int',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
