# Generated by Django 5.1 on 2024-12-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_generationprocess_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationprocess',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram id'),
        ),
    ]
