# Generated by Django 5.1 on 2024-12-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_alter_promptmodelsettings_and_or_and_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptmodelsettings',
            name='promt_russia',
            field=models.TextField(blank=True, null=True, verbose_name='Промпт на рус'),
        ),
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='and_or_and_you',
            field=models.CharField(choices=[('AND', 'И'), ('AND_YOU', 'И Вы')], max_length=300, verbose_name='И / И Вы'),
        ),
    ]
