# Generated by Django 5.1 on 2024-12-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_promptmodelsettings_promt_russia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='budget',
            field=models.CharField(choices=[('Z', '25 тыс. рублей'), ('X', '50 тыс. рублей'), ('C', '100 тыс. рублей'), ('V', '250 тыс. рублей'), ('F', '500 тыс. рублей'), ('L', '1 млн рублей')], max_length=1, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='interest',
            field=models.CharField(choices=[('A', 'Путешествия'), ('B', 'Недвижимость'), ('C', 'Развлечения'), ('D', 'Автомобили'), ('E', 'Саморазвитие'), ('F', 'Эмоции/Вдохновение')], max_length=1, verbose_name='Интерес'),
        ),
        migrations.CreateModel(
            name='LoggingProccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram id')),
                ('generation_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время на генерацию')),
                ('result_formula', models.FloatField(blank=True, null=True, verbose_name='Результат формулы')),
                ('user_price', models.FloatField(blank=True, null=True, verbose_name='Сумма')),
                ('user_category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Интерес')),
                ('gender', models.CharField(blank=True, max_length=255, null=True, verbose_name='Гендер')),
                ('time_invest', models.CharField(blank=True, max_length=255, null=True, verbose_name='На какой срок')),
                ('investor_risk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Риски')),
                ('generation_number', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='generation_number', to='bot_app.generationprocess', verbose_name='Процесс')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
