# Generated by Django 5.1.1 on 2024-12-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0010_remove_promptmodelsettings_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='budget_1',
            field=models.CharField(blank=True, choices=[('25 тыс', '25 тыс. рублей'), ('500 тыс', '50 тыс. рублей'), ('100 тыс', '100 тыс. рублей'), ('250 тыс', '250 тыс. рублей'), ('500 тыс', '500 тыс. рублей'), ('1 млн', '1 млн рублей')], max_length=500, null=True, verbose_name='Бюджет 1'),
        ),
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='budget_2',
            field=models.CharField(blank=True, choices=[('25 тыс', '25 тыс. рублей'), ('500 тыс', '50 тыс. рублей'), ('100 тыс', '100 тыс. рублей'), ('250 тыс', '250 тыс. рублей'), ('500 тыс', '500 тыс. рублей'), ('1 млн', '1 млн рублей')], max_length=500, null=True, verbose_name='Бюджет 2'),
        ),
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='budget_3',
            field=models.CharField(blank=True, choices=[('25 тыс', '25 тыс. рублей'), ('500 тыс', '50 тыс. рублей'), ('100 тыс', '100 тыс. рублей'), ('250 тыс', '250 тыс. рублей'), ('500 тыс', '500 тыс. рублей'), ('1 млн', '1 млн рублей')], max_length=500, null=True, verbose_name='Бюджет 3'),
        ),
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='interest_1',
            field=models.CharField(blank=True, choices=[('путешествия', 'Путешествия'), ('недвижимость', 'Недвижимость'), ('развлечения', 'Развлечения'), ('автомобили', 'Автомобили'), ('саморазвитие', 'Саморазвитие'), ('Эмоции/Вдохновение', 'Эмоции/Вдохновение')], max_length=500, null=True, verbose_name='Интерес 1'),
        ),
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='interest_2',
            field=models.CharField(blank=True, choices=[('путешествия', 'Путешествия'), ('недвижимость', 'Недвижимость'), ('развлечения', 'Развлечения'), ('автомобили', 'Автомобили'), ('саморазвитие', 'Саморазвитие'), ('Эмоции/Вдохновение', 'Эмоции/Вдохновение')], max_length=500, null=True, verbose_name='Интерес 2'),
        ),
    ]
