# Generated by Django 5.1.1 on 2024-12-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0011_alter_promptmodelsettings_budget_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptmodelsettings',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер промта'),
        ),
    ]
