# Generated by Django 5.1.1 on 2024-12-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0012_promptmodelsettings_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationprocess',
            name='format_photo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Формат фотки'),
        ),
    ]
