# Generated by Django 5.1.1 on 2024-12-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0013_generationprocess_format_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationprocess',
            name='process_end_time',
            field=models.DateTimeField(blank=True, help_text='Время окончания процесса (если процесс завершен)', null=True, verbose_name='Завершение'),
        ),
        migrations.AddField(
            model_name='generationprocess',
            name='process_start_time',
            field=models.DateTimeField(blank=True, help_text='Время старта процесса', null=True, verbose_name='Старт'),
        ),
        migrations.AddField(
            model_name='generationprocess',
            name='process_take_time',
            field=models.DurationField(blank=True, help_text='Сколько всего времени заняло исполнение процесса (если процесс завершен)', null=True, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='generationprocess',
            name='format_photo',
            field=models.CharField(blank=True, default='Вертикальный', max_length=255, null=True, verbose_name='Формат фотки'),
        ),
    ]
