# Generated by Django 5.1.1 on 2024-12-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0014_generationprocess_process_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingproccess',
            name='generation_time',
            field=models.DurationField(blank=True, help_text='Сколько всего времени заняло исполнение процесса (если процесс завершен)', null=True, verbose_name='Время выполнения'),
        ),
    ]
