# Generated by Django 5.1.1 on 2024-12-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0016_alter_loggingproccess_generation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingproccess',
            name='generation_time',
            field=models.CharField(blank=True, help_text='Сколько всего времени заняло исполнение процесса (если процесс завершен)', max_length=255, null=True, verbose_name='Время выполнения'),
        ),
    ]
