# Generated by Django 5.1.1 on 2024-12-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0018_alter_loggingproccess_generation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptmodelsettings',
            name='men_promt',
            field=models.TextField(blank=True, null=True, verbose_name='Мужской Промпт'),
        ),
        migrations.AddField(
            model_name='promptmodelsettings',
            name='women_promt',
            field=models.TextField(blank=True, null=True, verbose_name='Женский Промпт'),
        ),
    ]
