# Generated by Django 5.1.1 on 2024-12-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0019_promptmodelsettings_men_promt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='budget_1',
            field=models.CharField(blank=True, choices=[('25,0', '25 тыс. рублей'), ('500,0', '50 тыс. рублей'), ('100,0', '100 тыс. рублей'), ('250,0', '250 тыс. рублей'), ('500,0', '500 тыс. рублей'), ('1,0', '1 млн рублей')], max_length=500, null=True, verbose_name='Бюджет 1'),
        ),
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='budget_2',
            field=models.CharField(blank=True, choices=[('25,0', '25 тыс. рублей'), ('500,0', '50 тыс. рублей'), ('100,0', '100 тыс. рублей'), ('250,0', '250 тыс. рублей'), ('500,0', '500 тыс. рублей'), ('1,0', '1 млн рублей')], max_length=500, null=True, verbose_name='Бюджет 2'),
        ),
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='budget_3',
            field=models.CharField(blank=True, choices=[('25,0', '25 тыс. рублей'), ('500,0', '50 тыс. рублей'), ('100,0', '100 тыс. рублей'), ('250,0', '250 тыс. рублей'), ('500,0', '500 тыс. рублей'), ('1,0', '1 млн рублей')], max_length=500, null=True, verbose_name='Бюджет 3'),
        ),
    ]
