# Generated by Django 5.1.1 on 2024-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0022_alter_promptmodelsettings_interest_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptmodelsettings',
            name='and_or_and_you',
        ),
        migrations.AddField(
            model_name='promptmodelsettings',
            name='rolevaya',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ролевая'),
        ),
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='budget_1',
            field=models.CharField(blank=True, choices=[('25', '25 тыс. рублей'), ('50', '50 тыс. рублей'), ('100', '100 тыс. рублей'), ('250', '250 тыс. рублей'), ('500', '500 тыс. рублей'), ('1', '1 млн рублей')], max_length=500, null=True, verbose_name='Бюджет 1'),
        ),
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='budget_2',
            field=models.CharField(blank=True, choices=[('25', '25 тыс. рублей'), ('50', '50 тыс. рублей'), ('100', '100 тыс. рублей'), ('250', '250 тыс. рублей'), ('500', '500 тыс. рублей'), ('1', '1 млн рублей')], max_length=500, null=True, verbose_name='Бюджет 2'),
        ),
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='budget_3',
            field=models.CharField(blank=True, choices=[('25', '25 тыс. рублей'), ('50', '50 тыс. рублей'), ('100', '100 тыс. рублей'), ('250', '250 тыс. рублей'), ('500', '500 тыс. рублей'), ('1', '1 млн рублей')], max_length=500, null=True, verbose_name='Бюджет 3'),
        ),
    ]
