# Generated by Django 5.1.1 on 2024-12-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0023_remove_promptmodelsettings_and_or_and_you_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingproccess',
            name='textovka_new',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Готовая текстовка'),
        ),
        migrations.AlterField(
            model_name='promptmodelsettings',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='После'),
        ),
    ]
