# Generated by Django 5.1.1 on 2024-12-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0025_remove_loggingproccess_textovka_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingproccess',
            name='textovka_new',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Готовая текстовка'),
        ),
    ]
