# Generated by Django 5.1.1 on 2024-12-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0030_alter_loggingproccess_result_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingproccess',
            name='formul',
            field=models.TextField(blank=True, null=True, verbose_name='Результат формулы'),
        ),
    ]
