# Generated by Django 5.1.1 on 2024-12-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0031_loggingproccess_formul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggingproccess',
            name='formul',
        ),
        migrations.AddField(
            model_name='loggingproccess',
            name='process_start_time',
            field=models.DateTimeField(blank=True, help_text='Время старта процесса', null=True, verbose_name='Старт'),
        ),
    ]
