# Generated by Django 5.1.1 on 2024-12-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0032_remove_loggingproccess_formul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationprocess',
            name='path_on_tahe_photo',
            field=models.TextField(blank=True, help_text='path on tahe new photo', null=True),
        ),
    ]
