# Generated by Django 5.1.1 on 2024-12-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0033_generationprocess_path_on_tahe_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationprocess',
            name='is_alert_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
