# Generated by Django 5.1.1 on 2024-12-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0034_generationprocess_is_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationprocess',
            name='negative_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='Негативный Промпт'),
        ),
        migrations.AddField(
            model_name='promptmodelsettings',
            name='negative_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='Негативный Промпт'),
        ),
    ]
