# Generated by Django 5.1 on 2024-10-02 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StikerPackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(verbose_name='StikerPack Name')),
                ('main_pack_stiker', models.ImageField(blank=True, null=True, upload_to='main_stickers/', verbose_name='Main sticker')),
            ],
            options={
                'verbose_name': 'Созданный стикерпак',
                'verbose_name_plural': 'Созданные стикерпаки',
            },
        ),
        migrations.CreateModel(
            name='Generate_Stickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_set_name', models.CharField(max_length=250, verbose_name='Имя набора стикеров')),
                ('pack_created', models.BooleanField(default=False, verbose_name='Пак создан?')),
                ('ready_for_generation', models.BooleanField(default=False, verbose_name='Ready for Gen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticker_packs', to='bot_app.botuser', verbose_name='Пользователь')),
                ('stiker_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stickers.stikerpackconfig', verbose_name='Стикер пак')),
            ],
            options={
                'verbose_name': 'Пользовательский стикерпак',
                'verbose_name_plural': 'Пользовательские стикерпаки',
            },
        ),
        migrations.CreateModel(
            name='Stiker_output_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_photo', models.ImageField(blank=True, null=True, upload_to='stickers_photo/', verbose_name='Фото героя')),
                ('emoji', models.CharField(blank=True, max_length=5, null=True, verbose_name='Эмодзи')),
                ('original_photo_id', models.IntegerField(blank=True, null=True, verbose_name='original_photo_id')),
                ('stiker_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stickers.generate_stickers', verbose_name='Стикер пак')),
            ],
            options={
                'verbose_name': 'Фото после генерации',
                'verbose_name_plural': 'Фото после генерации',
            },
        ),
        migrations.CreateModel(
            name='Stiker_target_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(verbose_name='Photo name')),
                ('target_photo', models.ImageField(blank=True, null=True, upload_to='stickers_photo/', verbose_name='Фото героя')),
                ('emoji', models.CharField(blank=True, max_length=5, null=True, verbose_name='Эмодзи')),
                ('mask', models.ImageField(blank=True, null=True, upload_to='mask/', verbose_name='Маска героя')),
                ('stiker_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stickers.stikerpackconfig', verbose_name='Стикер пак')),
            ],
            options={
                'verbose_name': 'Фото для генерации',
                'verbose_name_plural': 'Фото для генерации',
            },
        ),
    ]
